# This is a basic workflow to help you get started with Actions

name: Deploy Portofolio Website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
			-master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
		steps:
			- uses: actions/checkout@v1
			- name: Use Node Js
				uses: actions/setup-node@v1
				with:
					node-version: '10.x'

			- name: npm install, build and test
				run: |
					npm install --production
					npm run build
					
			- name: push to master 
				run: |
					cd dist
					git add .
					git commit -m "deploy"
					git push
					
 
